### ISSUE TITLE
flathub.org and flathub repo still have 0.7.0

### ISSUE THREAD

**Issue by Marzal** [flathub/im.kaidan.kaidan#1]
In the json exits the 0.8, but I think some pipeline failed and the upgrade didn't apply

**Comment by binyamin** [comment]
@Marzal in the meantime, you can [use KDE's flatpak repo](https://invent.kde.org/network/kaidan/-/wikis/using/flatpak) instead, which has 0.8.0.

**Comment by Marzal** [comment]
Thanks, it says 0.8.0 but it's really 0.9.0 nighty. At least works :smile:  :+1:
